大・専門学校のクラスを実装
ohtya/java-practice pull request #11
Opened 2020-11-05 15:52 UTC by scarlet1990

実装

2020-12-17 14:35 UTC, ohtya requested changes
コメントしました。
他のクラスにも同じことが言えるので一部のクラスにのみコメントしています。

2020-12-17 14:35 UTC, ohtya commented on src/main/java/cinema/ticket/domain/DiscountRule.java
> +    long ticketFee();
割引適用後のチケット料金を返却するのかな？
割引ルールインターフェースなので、割引率 or 割引額を返却するのほうが良いのでは？

2020-12-17 14:35 UTC, ohtya commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +    private boolean isSenior;
Visitor に持たせたほうが良いのでは？

2020-12-17 14:35 UTC, ohtya commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +        isSenior = (60 <= visitor.getAge());
外から渡すか、シネマシティズン×シニアのクラスを作りましょう。
このメソッドを実行したときに内部のステータスが変わるのは好ましくないです。

おすすめはクラスを作ることです。

2020-12-17 14:35 UTC, ohtya commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +        if (isSenior) {
シネマシティズン×シニアのクラスを作成したほうが良いです。
もし、平日は1,100円などに仕様が変わったときに変更に弱い作りになっています。（どんどんif文が増えてしまう）

2020-12-17 14:35 UTC, ohtya commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +        final var time = LocalDateTime.now();
時間は外から渡せるようにしたほうがユニットテストが容易になります。
また time ではなく nowDateTime など一目で何を表すかわかる名前にしましょう。

全ての変数の suffix にクラス名を付与する必要はないです。
時間を表現するクラスが多く存在するため、日時系は付与してあげたほうが可読性が高いと個人的には思ってます。

2020-12-17 14:35 UTC, ohtya commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +            return 1000;
もし、平日×レイトショーの価格が改訂されたらどうしますか？
このまあだと if 文が増える未来が視えますね。

少し考えてみてください！

2021-02-01 16:47 UTC, scarlet1990 commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +            return 1000;
色々やるために実装増やしたんですが、ちょっと結局変わらんのちゃうかと思って途中まで作って切り上げました・・・
また明日に詳細こんな感じで～っての説明しようと思います。(今日は寝ます)

2021-05-02 10:31 UTC, scarlet1990 commented on src/main/java/cinema/ticket/domain/DiscountRule.java
> +    long ticketFee();
考慮を忘れておった。考え中。

2021-05-02 10:31 UTC, scarlet1990 commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +    private boolean isSenior;
持たせました。

2021-05-02 10:38 UTC, scarlet1990 commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +        isSenior = (60 <= visitor.getAge());
Visitorクラスにシニアであるかの区分を持たせました。
ただVisitorTypeのEnumにシニアの区分があるくせにこのフラグと使ってるところが別々なので気持ち悪さが何とも。
もしかしてシニアとクラス分けるならVisitorTypeを使えばいいのでは・・・

2021-05-02 10:39 UTC, scarlet1990 commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +        if (isSenior) {
シニアと分けました。

2021-05-02 10:39 UTC, scarlet1990 commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +        final var time = LocalDateTime.now();
引数に日付を取るようにしました。

2021-05-02 10:39 UTC, scarlet1990 commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +            return 1000;
とりあえず平日の`通常／レイト`で処理は分けるようにはしました。

2021-05-02 11:53 UTC, ohtya commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +        isSenior = (60 <= visitor.getAge());
`VistorType` をうまく利用できるとより良いですね。
良い気づきだと思います。

2021-05-02 11:57 UTC, ohtya commented on src/main/java/cinema/ticket/domain/rule/CinemaCitizen.java
> +        final var time = LocalDateTime.now();
もし、この日付を外から渡せないときにはどういう手順を踏んでリファクタリングするか、考えてみると学びにつながると思います。
（いろんなクラスから利用されていて、シグネチャを変更するのが容易ではないケースです）

1. 同クラス内に時間を返すメソッドを用意する
2. テストクラスで、好きな時間を返せるように extends する
3. テストメソッドで、好きな時間を返すように Override する

ようにすると、影響範囲を狭めながらテスト容易性を高めることができます。
カバレッジがカバーしている範囲ならテストができる、と判断して自由にリファクタリングできます。

2021-05-02 12:19 UTC, ohtya approved these changes
ユニットテスト通っているのでヨシ！

2021-05-02 12:19 UTC, merged