Feature/yt weekend
ohtya/java-practice pull request #5
Opened 2020-02-09 14:57 UTC by ytttt-2kab

java11対応を入れて、休日割引を途中まで作りました。
祝日判定と休日またぎ判定がまだ入っていません。

2020-02-09 15:31 UTC, ohtya requested changes
コメントしました！

2020-02-09 15:31 UTC, ohtya commented on build.gradle
> +}
注意
私のPRがdevelopにマージされたらコンフリクトすると思います。
とりあえず記憶しておいてください。

コンフリクト対応も学びの一つとしてやっていきましょう。

2020-02-09 15:31 UTC, ohtya commented on gradle/wrapper/gradle-wrapper.properties
> +zipStoreBase=GRADLE_USER_HOME
ここもコンフリクトすると思う。

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/model/DrivingInfo.java
> +    public Date admissionTime;
[imo]
`LocalDateTime` を使ったほうが良いと思う。
他の `Date` も同様。

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/model/DrivingInfo.java
> +    public Date exitTime;
[imo]
`exitAt` が良いと思う。
日時の場合は xxxAt 、 日付の場合は xxxOn と命名するパターンがあります。

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/model/DrivingInfo.java
> +    public Date exitTime;
他の項目名も同様

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +    private static final long discountRate = 30;
[ask]
今は休日割引の割引率が1つしかないけど、複数に増えたときはどうします？

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +    private static final long discountRate = 30;
[imo]
定数はコンスタントケースで命名しましょう。

参考
https://qiita.com/am_nimitz3/items/7b01af53751dba5d8fb1

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +        if (info.carModel == CarModel.KEI || info.carModel == CarModel.ORDINARY) {
[imo]
stream 使うとよりシンプルになります。

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +        return 0;
[ask]
割引できないときに0を返すか、割引できないときはこのメソッドを呼ばせないか・・・。
どっちが優しいと思いますか？

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +     * FIXME:祝日判定が入っていない（土日判定のみ）
祝日は一旦おいといて良いと思う。
googleカレンダーなどから祝日を取得してキャッシュしておく処理が必要になるので。

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +        Calendar cal = Calendar.getInstance();
[imo]
`Calendar` は使いたくないなあ。
`LocalDateTime` に変えてみませんか？

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +        return false;
[imo]
`return` が冗長かな。
この場合は if 文の結果がそれ即ち戻り値だと思う。

2020-02-09 15:31 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +}
あー、改行コードをLFにする設定しないとダメかも。

2020-02-09 15:31 UTC, ohtya commented on src/test/java/etc/discount/service/WeekendDiscountServiceTest.java
> +            Date exitTime = df.parse("2020/02/09 13:00:00");
[imo]
`LocalDateTime` にすると幸せになれます。
`LocalDateTime.of()` で検索！

2020-02-16 10:47 UTC, ytttt-2kab commented on src/main/java/etc/discount/model/DrivingInfo.java
> +    public Date admissionTime;
LocalDateTimeを使うように変更しました。

2020-02-16 10:47 UTC, ytttt-2kab commented on src/main/java/etc/discount/model/DrivingInfo.java
> +    public Date exitTime;
日時系の命名をxxxAtに変更しました。

2020-02-16 10:48 UTC, ytttt-2kab commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +    private static final long discountRate = 30;
定数をコンスタントケースに修正しました。

2020-02-16 10:48 UTC, ytttt-2kab commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +        Calendar cal = Calendar.getInstance();
LocalDateTimeを使うように変更しました。

2020-02-16 10:49 UTC, ytttt-2kab commented on src/test/java/etc/discount/service/WeekendDiscountServiceTest.java
> +            Date exitTime = df.parse("2020/02/09 13:00:00");
LocalDateTimeを使うように変更しました。

2020-02-16 11:18 UTC, ytttt-2kab commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +        if (info.carModel == CarModel.KEI || info.carModel == CarModel.ORDINARY) {
streamはListみたいな複数から絞り込んだりするのに使うんだと思っていたのですが、どういう使い方をすればいいでしょうか？
https://docs.oracle.com/javase/jp/8/docs/api/java/util/stream/Stream.html

2020-02-16 16:26 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +        if (info.carModel == CarModel.KEI || info.carModel == CarModel.ORDINARY) {
インスタンス生成時にenumから条件に合致するモノだけ抽出したコレクション(リストでいい)を用意しておく。
コレクションの車種と1つでもマッチするなら、って処理をstreamで書く。

2020-02-20 10:40 UTC, ohtya commented on src/main/java/etc/discount/service/WeekendDiscountService.java
> +        if (info.carModel == CarModel.KEI || info.carModel == CarModel.ORDINARY) {
streamじゃなくてもcontainsで良いか

2020-06-08 13:57 UTC, closed without merging