一区切りまで実装
ohtya/java-practice pull request #6
Opened 2020-02-19 17:07 UTC by scarlet1990

一区切りまで実装しました。

一応計算できるようにはなっています。
いろいろTODO部分が多く、見苦しいと思われますが、そもそもの方針や構成にツッコミを入れていただけると助かります。

2020-02-19 17:42 UTC, ohtya requested changes
コメントしました！

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +    private Route isLocal() {
Ronteを走行情報にもたせてよいと思う

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/model/DrivingInformation.java
> +    private String enteringPoint;
位置は何のためにもたせます？
距離によって割引率変わるんでしたっけ？

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/model/DrivingInformation.java
> +    public CarModel getType() {
素直にmodelで良い気がします

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/model/DrivingInformation.java
> +public class DrivingInformation {
情報クラス自体が情報なのでInformationをつけるのは冗長かと。

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/DiscountService.java
> -    long add(long x, long y);
サンプルは消さなくても良いよ

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +        this.info = info;
コンストラクタで渡してimmutableにするのは悪くない。
でも走行情報ってそもそも状態として保持しておく必要あります？

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +    public long calculate(long price) {
priceだけ走行情報の外に出したのは何故？
(単純に気になった)

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +            // TODO ポイントによる減算は未実装、固定で50パーセント割引（還元）とする。
朝夕割引の利用回数での割引のことかな？

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +        } else if ((this.info.getType() == KEI || this.info.getType() == ORDINARY) && // 休日割引
コメントで補足しないと何割引かわからないのはキッツいね…。
メソッド分割してメソッド名で伝わるようにするのはどうだろう？

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +        DayOfWeek week = info.getEnteringDate().getDayOfWeek();
var使えるよ

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +        return (week == DayOfWeek.SATURDAY || week == DayOfWeek.SUNDAY);
streamを使って判定するとよりシンプルになります

2020-02-19 17:42 UTC, ohtya commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +    private Boolean isMorning() {
朝夕のチェックって判定する時間が異なるだけでやってること同じだよね？
再利用可能なように実装すると良いと思う

2020-02-19 17:42 UTC, ohtya commented on src/test/java/etc/discount/service/EtcDiscountServiceTest.java
> +    void calculate_1() {
メソッド名でテスト内容が伝わるようにしよう

2020-02-19 17:42 UTC, ohtya commented on src/test/java/etc/discount/service/EtcDiscountServiceTest.java
> +        assertEquals(expected, actual);
複数のassertがあるのは悪くはないけど、異なる事前準備や確認内容が1つのテストメソッドに含まれているのはよろしくないので、別のメソッドにわけたほうがよい

2020-02-21 16:10 UTC, scarlet1990 commented on src/main/java/etc/discount/model/DrivingInformation.java
> +    private String enteringPoint;
どこからどこまでで料金が決定するはずなのでその為の情報として持たせました。

2020-02-21 16:12 UTC, scarlet1990 commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +        this.info = info;
確かにそうですね。
割引のクラスなのでそこに持たせるのは不自然かもしれないです。ので消しときます。
引数でもらってやるようにします。

2020-02-21 16:14 UTC, scarlet1990 commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +    public long calculate(long price) {
走行情報に持たせてもいいと思ったのですが本来は普通に料金計算とかもろもろするサービスが存在してそこが算出した料金をもとに割引を出すサービスって役割と考えました。
(結局走行情報を持たせてしまったので本末転倒感ありますが・・・)

2020-02-21 16:15 UTC, scarlet1990 commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +            // TODO ポイントによる減算は未実装、固定で50パーセント割引（還元）とする。
その通りです。
ここだけ割引ではなくポイント加算だったのでどうしようかと思いました。

2020-02-21 16:16 UTC, scarlet1990 commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +        } else if ((this.info.getType() == KEI || this.info.getType() == ORDINARY) && // 休日割引
そうですよね。ちょっと思いながら書いてました。
メソッド増やしすぎるのアレかと思いましたけど1メソッド冗長や可読性落とすならそっちにしようと思います。

2020-02-21 16:17 UTC, scarlet1990 commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +        DayOfWeek week = info.getEnteringDate().getDayOfWeek();
理解していないのですがvarにすると何かいいことがあるんでしょうか・・・

2020-02-24 16:23 UTC, scarlet1990 commented on src/main/java/etc/discount/service/EtcDiscountService.java
> +    private Route isLocal() {
Route持たせました。

2020-02-24 16:26 UTC, scarlet1990 commented on src/main/java/etc/discount/model/DrivingInformation.java
> +    public CarModel getType() {
変数名のことでしょうか。

2020-02-24 16:27 UTC, scarlet1990 commented on src/main/java/etc/discount/model/DrivingInformation.java
> +public class DrivingInformation {
Informationを消しました。

2020-02-24 16:30 UTC, scarlet1990 commented on src/main/java/etc/discount/service/DiscountService.java
> -    long add(long x, long y);
戻しました。

2020-03-03 17:45 UTC, scarlet1990 commented
コメント返しきれてない上に指摘消化でき切れていませんが新たにStateパターン盛り込んだ奴実装だけしました。
テストでエラーでてるのでバグってますが、修正は明日以降やろうと思います。。。。
気が向いたら見てみてください。
終わったらまた連絡しますのでそのあとでも。。。

2020-06-08 13:57 UTC, closed without merging